import { useState, useEffect, useRef } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import axios from 'axios'
import { CheckCircle, Circle, ArrowLeft, Calendar, Edit2, Flame, Save, X, Download, FileText, Image as ImageIcon, ChevronDown } from 'lucide-react'
import TimeframeHeader from '../components/TimeframeHeader'

// Export Libraries
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx'
import { saveAs } from 'file-saver'

import { API_URL } from '../config'
import { useAuth } from '@clerk/clerk-react'

export default function RoadmapView() {
    const { userId } = useAuth()
    const { id } = useParams()
    const navigate = useNavigate()
    const [tasks, setTasks] = useState([])
    const [roadmap, setRoadmap] = useState(null)
    const [timeframes, setTimeframes] = useState([])
    const [isEditingName, setIsEditingName] = useState(false)
    const [newName, setNewName] = useState('')

    // Export State
    const [isExportMenuOpen, setIsExportMenuOpen] = useState(false)
    const [isExporting, setIsExporting] = useState(false)
    const roadmapRef = useRef(null) // Ref for PDF capture

    useEffect(() => {
        fetchData()
        fetchTimeframes()
    }, [id])

    const fetchData = async () => {
        try {
            const [rRes, tRes] = await Promise.all([
                axios.get(`${API_URL}/roadmaps/${id}`),
                axios.get(`${API_URL}/roadmaps/${id}/tasks`)
            ])
            setRoadmap(rRes.data)
            setNewName(rRes.data.name)
            setTasks(tRes.data)
        } catch (error) {
            console.error("Failed to fetch data", error)
        }
    }

    const fetchTimeframes = async () => {
        try {
            const res = await axios.get(`${API_URL}/roadmaps/${id}/timeframes`)
            setTimeframes(res.data)
        } catch (error) {
            console.error("Failed to fetch timeframes", error)
        }
    }

    const toggleTask = async (taskId, currentStatus) => {
        setTasks(tasks.map(t => t.id === taskId ? { ...t, is_done: !currentStatus } : t))
        try {
            await axios.put(`${API_URL}/tasks/${taskId}/status`, { is_done: !currentStatus }, {
                headers: { 'X-Clerk-User-Id': userId }
            })
        } catch (error) {
            console.error("Failed to update task", error)
            setTasks(tasks.map(t => t.id === taskId ? { ...t, is_done: currentStatus } : t))
        }
    }

    const saveName = async () => {
        if (!newName.trim()) return
        try {
            await axios.put(`${API_URL}/roadmaps/${id}/name`, { name: newName }, {
                headers: { 'X-Clerk-User-Id': userId }
            })
            setRoadmap({ ...roadmap, name: newName })
            setIsEditingName(false)
        } catch (error) {
            console.error("Failed to rename roadmap", error)
        }
    }

    // Group tasks by timeframe
    const groupedTasks = tasks.reduce((acc, task) => {
        const group = task.timeframe_label || "Unassigned"
        if (!acc[group]) acc[group] = []
        acc[group].push(task)
        return acc
    }, {})

    const totalTasks = tasks.length
    const completedTasks = tasks.filter(t => t.is_done).length
    const percentage = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0

    // --- Export Functions ---

    const handleExportPDF = async () => {
        setIsExporting(true)
        setIsExportMenuOpen(false)
        try {
            const element = roadmapRef.current
            const canvas = await html2canvas(element, {
                scale: 2, // High resolution
                backgroundColor: '#050505', // Match dark theme
                useCORS: true
            })

            const imgData = canvas.toDataURL('image/png')
            const pdf = new jsPDF('p', 'mm', 'a4')
            const pdfWidth = pdf.internal.pageSize.getWidth()
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
            pdf.save(`${roadmap.name.replace(/\s+/g, '_')}_Roadmap.pdf`)
        } catch (err) {
            console.error("PDF Export failed", err)
            alert("Failed to generate PDF")
        } finally {
            setIsExporting(false)
        }
    }

    const handleExportDoc = async () => {
        setIsExporting(true)
        setIsExportMenuOpen(false)
        try {
            // Build Document Structure
            const children = [
                new Paragraph({
                    text: roadmap.name,
                    heading: HeadingLevel.TITLE,
                    spacing: { after: 300 }
                }),
                new Paragraph({
                    text: `Generated by TRAQO - ${new Date().toLocaleDateString()}`,
                    spacing: { after: 500 }
                })
            ]

            // Iterate Groups
            Object.entries(groupedTasks).forEach(([group, groupTasks]) => {
                children.push(
                    new Paragraph({
                        text: group,
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 400, after: 200 }
                    })
                )

                groupTasks.forEach(task => {
                    children.push(
                        new Paragraph({
                            text: `${task.is_done ? '[x]' : '[ ]'} ${task.title}`,
                            bullet: { level: 0 }
                        })
                    )
                })
            })

            const doc = new Document({
                sections: [{ properties: {}, children }]
            })

            const blob = await Packer.toBlob(doc)
            saveAs(blob, `${roadmap.name.replace(/\s+/g, '_')}.docx`)
        } catch (err) {
            console.error("Word Export failed", err)
            alert("Failed to generate Word Doc")
        } finally {
            setIsExporting(false)
        }
    }


    if (!roadmap) return <div className="loading">Loading...</div>

    return (
        <div className="roadmap-view" ref={roadmapRef}>
            <div className="view-header" data-html2canvas-ignore> {/* Ignore header in PDF if desired, or keep it. Let's keep it but maybe hide buttons? */}
                <div className="header-left">
                    <Link to="/">
                        <button className="btn-primary back-btn">
                            <ArrowLeft size={18} /> Back
                        </button>
                    </Link>
                </div>

                <div className="header-right" style={{ position: 'relative' }}>

                    {/* Export Dropdown */}
                    <div className="export-menu-container">
                        <button
                            className="btn-primary"
                            onClick={() => setIsExportMenuOpen(!isExportMenuOpen)}
                            disabled={isExporting}
                        >
                            {isExporting ? <span className="spinner-small"></span> : <Download size={16} style={{ marginRight: '8px' }} />}
                            Save As
                            <ChevronDown size={14} style={{ marginLeft: '6px' }} />
                        </button>

                        <AnimatePresence>
                            {isExportMenuOpen && (
                                <motion.div
                                    className="dropdown-menu glass-panel"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: 10 }}
                                >
                                    <button className="dropdown-item" onClick={handleExportPDF}>
                                        <ImageIcon size={16} /> PDF (Image)
                                    </button>
                                    <button className="dropdown-item" onClick={handleExportDoc}>
                                        <FileText size={16} /> Word Doc
                                    </button>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>

                    <Link to={`/edit/${id}`}>
                        <button className="btn-primary">
                            <Edit2 size={16} style={{ marginRight: '8px' }} />
                            Edit
                        </button>
                    </Link>
                </div>
            </div>

            <div className="roadmap-hero">
                <div className="hero-top">
                    {isEditingName ? (
                        <div className="edit-name-container">
                            <input
                                type="text"
                                value={newName}
                                onChange={(e) => setNewName(e.target.value)}
                                className="name-input"
                                autoFocus
                            />
                            <button className="icon-btn save-btn" onClick={saveName}>
                                <Save size={20} />
                            </button>
                            <button className="icon-btn cancel-btn" onClick={() => setIsEditingName(false)}>
                                <X size={20} />
                            </button>
                        </div>
                    ) : (
                        <div className="title-container">
                            <h2>{roadmap.name}</h2>
                            <button className="icon-btn edit-name-btn" onClick={() => setIsEditingName(true)} data-html2canvas-ignore>
                                <Edit2 size={16} />
                            </button>
                        </div>
                    )}
                    <span className="date-badge">
                        <Calendar size={14} /> {new Date(roadmap.created_at).toLocaleDateString()}
                    </span>
                </div>

                <div className="progress-section large">
                    <div className="progress-info">
                        <span className="progress-text">{completedTasks}/{totalTasks} tasks completed</span>
                        <span className="progress-percentage">{percentage}%</span>
                    </div>
                    <div className="progress-bar large">
                        <motion.div
                            className="progress-fill"
                            initial={{ width: 0 }}
                            animate={{ width: `${percentage}%` }}
                            transition={{ duration: 0.8 }}
                        />
                    </div>
                </div>
            </div>

            <div className="timeline">
                {Object.entries(groupedTasks).map(([group, groupTasks], groupIndex) => {
                    const timeframeData = timeframes.find(tf => tf.label === group)
                    return (
                        <motion.div
                            key={group}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: groupIndex * 0.1 }}
                            className="timeframe-group"
                        >
                            {timeframeData ? (
                                <TimeframeHeader
                                    timeframe={timeframeData}
                                    onUpdate={fetchTimeframes}
                                />
                            ) : (
                                <h3 className="timeframe-label">{group}</h3>
                            )}
                            <div className="tasks-list">
                                {groupTasks.map((task) => (
                                    <div
                                        key={task.id}
                                        className={`task-item glass-panel ${task.is_done ? 'done' : ''}`}
                                        onClick={() => toggleTask(task.id, task.is_done)}
                                    >
                                        <div className={`custom-checkbox ${task.is_done ? 'checked' : ''}`} />
                                        <span className="task-title">{task.title}</span>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    )
                })}
            </div>

            <style>{`
                .export-menu-container {
                    position: relative;
                }
                .dropdown-menu {
                    position: absolute;
                    top: 100%;
                    right: 0;
                    margin-top: 0.5rem;
                    background: #1a1a2e;
                    border: 1px solid rgba(255,255,255,0.1);
                    border-radius: 12px;
                    padding: 0.5rem;
                    display: flex;
                    flex-direction: column;
                    gap: 4px;
                    min-width: 160px;
                    z-index: 50;
                    box-shadow: 0 10px 40px rgba(0,0,0,0.5);
                }
                .dropdown-item {
                    display: flex;
                    align-items: center;
                    gap: 10px;
                    background: transparent;
                    border: none;
                    color: #fff;
                    padding: 0.6rem 1rem;
                    border-radius: 8px;
                    cursor: pointer;
                    text-align: left;
                    font-size: 0.9rem;
                    transition: all 0.2s;
                }
                .dropdown-item:hover {
                    background: rgba(255,255,255,0.1);
                }
                .spinner-small {
                    width: 16px;
                    height: 16px;
                    border: 2px solid rgba(255,255,255,0.3);
                    border-top: 2px solid white;
                    border-radius: 50%;
                    animation: spin 1s linear infinite;
                    display: inline-block;
                    margin-right: 8px;
                }
                @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
            `}</style>
        </div>
    )
}
